# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    user_service:
        class: UserBundle\Services\UserService
        arguments: ["@doctrine.orm.default_entity_manager"]

    task_service:
        class: UserBundle\Services\TaskService
        arguments: ["@doctrine.orm.default_entity_manager"]

    contact_service:
        class: UserBundle\Services\ContactService
        arguments: ["@doctrine.orm.default_entity_manager"]

    email_service:
        class: UserBundle\Services\EmailService
        arguments: ["@doctrine.orm.default_entity_manager", '@mailer', '@service_container']