<?php

namespace UserBundle\Repository;

use PDO;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Función que te devuelve todas las tareas
     * 
     * @author Pablo López <pablo.lopez@eurotransportcar.com>
     *
     * @return $tasks
     */
    public function getTasks() {
        
        $sql = 
            'SELECT
                t.id                                        "id",
                t.title                                     "title",
                DATE_FORMAT(t.created_at, "%d/%m/%Y %H:%i") "date",
                CONCAT(u.first_name, " ", u.last_name)      "user",
                t.status                                    "status"
            FROM
                tasks t
            LEFT JOIN 
                users u ON u.id = t.user_id
            ORDER BY
                t.id DESC'
        ;

        try {
            $query = $this->getEntityManager()->getConnection()->prepare($sql);
            $query->execute();
            $tasks = $query->fetchAll(\PDO::FETCH_ASSOC);
        } catch (\Throwable $th) {
            throw $th;
        }

        return $tasks;
    }

    /**
     * Función que te actualiza el estado de la tarea
     * 
     * @author Pablo López <pablo.lopez@eurotransportcar.com>
     *
     * @param $task
     * @param $status
     * @param $needPersist
     * @return boolean
     */
    public function updateStatus($task, $status = null, $needPersist = false) {
        
        try {
            $em = $this->getEntityManager();
            $task->setStatus($status);

            if ($needPersist) {
                $em->persist($task);
            }

            $em->flush();
        } catch (\Throwable $th) {
            return false;
        }

        return true;
    }

    /**
     * Función que te elimina una tarea
     * 
     * @author Pablo López <pablo.lopez@eurotransportcar.com>
     *
     * @param $task
     * @return boolean
     */
    public function removeTask($task) {
        try {
            $em = $this->getEntityManager();
            $em->remove($task);
            $em->flush();
        } catch (\Throwable $th) {
            return false;
        }

        return true;
    }
}