user_index:
    path:       /index
    defaults:   { _controller: UserBundle:User:index }

user_add:
    path:       /add
    defaults:   { _controller: UserBundle:User:add }

user_create:
    path:       /create
    defaults:   { _controller: UserBundle:User:create }
    methods: POST

user_edit:
    path:       /edit/{id}
    defaults:   { _controller: UserBundle:User:edit }

user_update:
    path:       /update/{id}
    defaults:   { _controller: UserBundle:User:update }
    methods:    [POST, PUT]

user_view:
    path:       /view/{id}
    defaults:   { _controller: UserBundle:User:view }

user_delete:
    path:       /delete/{id}
    defaults:   { _controller: UserBundle:User:delete }
    methods:    [POST, DELETE]

user_redirect_add:
    path:       /create
    defaults:
        _controller: UserBundle:User:add
        path: /add
        permanent: true

user_redirect_edit:
    path:       /update/{id}
    defaults:
        _controller: UserBundle:User:edit
        path: /edit{id}
        permanent: true